// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pampxaxkcobhpfeuslcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhbXB4YXhrY29iaHBmZXVzbGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODU0NjMsImV4cCI6MjA3MDY2MTQ2M30.tB3YHUxxb3jsuKNew8ophLRV-16yFV3UUMG0-IcD5_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});